
#Q5 Display the Supplier details who can supply more than one product.

SELECT SUP.SUPP_ID,SUP.SUPP_NAME,SUP.SUPP_CITY,SUP.SUPP_PHONE FROM  SUPPLIER SUP INNER JOIN  (
SELECT * FROM SUPPLIER_PRICING GROUP BY SUPP_ID HAVING COUNT(*)>1 ) AS SP ON
SUP.SUPP_ID=SP.SUPP_ID
 




